import turtle
import random
import time
grass = turtle.Turtle()
grass.color("#348C31")
grass.hideturtle()
grass.speed(150)
grass.penup()
grass.goto(-1000,0)
grass.pendown()

sky = turtle.Turtle()
sky.color("#87CEEB")
sky.hideturtle()
sky.speed(150)
sky.pensize(500)
sky.penup()
sky.goto(0, 250)
sky.pendown()
sky.forward(800)
sky.left(180)
sky.forward(1600)

floor = turtle.Turtle()
floor.color("#74663b")
floor.hideturtle()
floor.speed(150)
floor.pensize(500)
floor.penup()
floor.goto(0, -250)
floor.pendown()
floor.forward(800)
floor.left(180)
floor.forward(1600)

numbers = turtle.Turtle()
numbers.penup()
numbers.hideturtle()

screen = turtle.Screen()

def ground():
    grass.pensize(15) 
    grass.forward(random.randint(10,30))

def blades():
    x  = random.randint(30,60)
    grass.pensize(random.randint(5,15))
    grass.left(90)
    grass.forward(x)
    grass.right(180)
    grass.forward(x)
    grass.left(90)

def repeat():
	blades()
	ground()
	blades()
	ground()
	blades()
	ground()
	blades()
	ground()
	blades()
	ground()
	blades()
	ground()
	blades()
	ground()
	blades()
	ground()
	blades()
	ground()

repeat()
repeat()
repeat()
repeat()
repeat()
repeat()
repeat()
repeat()
repeat()
repeat()
repeat()

def num1():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num2():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num3():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num4():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num5():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num6():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num7():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num8():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)     
	numbers.write(random.randint(1, 9), font=('arial', 50))
def num9():
	numbers.clear()
	numbers.goto(-130, 100)
	numbers.write("the correct number is...", font=('arial', 25))
	time.sleep(1)
	numbers.clear()
	numbers.goto(0, 100)
	numbers.write(random.randint(1, 9), font=('arial', 50))

numbers.goto(-180, 100)
numbers.write("welcome to the game.", font=('arial', 25))
time.sleep(1)
numbers.clear()
numbers.goto(-300, 100)
numbers.write("press a number key to make a guess!", font=('arial', 25))
screen.onkey(num1,'1')
screen.onkey(num2,'2')
screen.onkey(num3,'3')
screen.onkey(num4,'4')
screen.onkey(num5,'5')
screen.onkey(num6,'6')
screen.onkey(num7,'7')
screen.onkey(num8,'8')
screen.onkey(num9,'9')
screen.listen()
